is_versioned: "bean is versioned?" {
	shape: hexagon
}

std_update: "standard update process"
is_versioned -> std_update: NO
std_update -> no_processing

component_has_changes: "data modified?" {
	shape: hexagon
}
is_versioned -> component_has_changes: YES

no_processing: "no more processing required"
component_has_changes -> no_processing: NO

is_component: "is VB component?" {
	shape: hexagon
}
component_has_changes -> is_component: YES

container_in_use: "is container in use?" {
	shape: hexagon
}
is_component -> container_in_use: YES
container_in_use -> std_update: NO

container_duplicate: "duplicate container & increment version"
copy_component_inc: "update VB & increment version"
copy_all_components: "duplicate all sibling components with incremented version & attach them to new container"
container_in_use -> container_duplicate: YES
container_duplicate -> copy_component_inc -> copy_all_components

is_container1: "is VB container?" {
	shape: hexagon
}
copy_all_components -> is_container1
is_container1 -> no_processing: NO

components_duplicate: "duplicate all subcomponents with incremented version & attach them to VB"
is_container1 -> components_duplicate: YES
components_duplicate -> no_processing


is_in_use: "is VB in use?" {
	shape: hexagon
}
is_component -> is_in_use: NO
is_in_use -> std_update: NO

is_version_required: "is versioning required" {
	shape: hexagon
}
is_in_use -> is_version_required: YES
is_version_required -> std_update: NO

container_duplicate2: "duplicate VB & increment version"
is_version_required -> container_duplicate2: YES

is_container2: "is VB container?" {
	shape: hexagon
}
container_duplicate2 -> is_container2
is_container2 -> no_processing: NO
is_container2 -> components_duplicate: YES
