package org.beanmaker.v2.codegen;

import java.text.DateFormat;

import java.util.Locale;

public class SourceFiles {

    public static void addCommentAndVersion(StringBuilder buf) {
        buf.append("// Generated by BeanMaker V2, on ");
        buf.append(DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, Locale.ENGLISH).format(new java.util.Date()));
        buf.append("\n");
        buf.append("// Library Version #");
        buf.append(Version.get());
        buf.append("\n\n");
    }

    public static String getCommentAndVersion() {
        StringBuilder buf = new StringBuilder();
        addCommentAndVersion(buf);
        return buf.toString();
    }

    public static String getCommentAndVersionForPropertyFile() {
        return getCommentAndVersion().replaceAll("//", "#");
    }

    public static String chopId(String nameWithId) {
        if (!nameWithId.startsWith("id"))
            throw new IllegalArgumentException(nameWithId + " does not start with 'id'");

        return nameWithId.substring(2, nameWithId.length());
    }

}
